# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 197b0df2c5bbd4e0fc1264cc321f23cd716d3ff39eba3df89bfff29386ce88d831a0dda24a0f4662b5c87f1b093dd6555ad4a796974bd36d072f4d9b0486d2f2

test:
  secret_key_base: 248bca3bf101e5d8e8fc871e7957ad2f16bbe5381344271e536d9340be56ee1e1f6aa62d9885e18a71e38921a7fed14854ca31895721b823fb478664793a91e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
